logging:
  level:
    com.wangjun.modules.*: debug

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true&serverTimezone=UTC
    username: root
    password: new_pass

obj:
  list:
    - name: 张三
      age: 20
    - name: 李四
      age: 21
    - name: 王五
      age: 18
