logging:
  level:
    com.wangjun.modules.*: debug

spring:
  datasource:
    url: jdbc:mysql://39.108.37.201:3306/test?useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true
    username: root
    password: WangJun-20190705!